apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata: 
  labels:
    release: prometheus 
  name: pod-rules
spec:
  groups:
    - name: pod 
      rules:
        - alert: PodNotRunning 
          expr: kube_pod_status_phase{phase!="Running"} > 0 
          for: 1m 
          labels: 
            severity: critical 
          annotations: 
            summary: Pod {{$labels.pod}} is not running 
     